import { useEffect, useState, type FormEvent } from 'react';
import { Edit2, FolderTree, Plus, Trash2 } from 'lucide-react';
import { categoryApi, type Category } from '../../services/api/category';
import { ConfirmDialog, EmptyState, Feedback, LoadingState, Modal, PageHeader, StatusBadge, controlClass, labelClass, primaryButtonClass, secondaryButtonClass } from '../../components/ui';

export function CategoryManager() {
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showModal, setShowModal] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Category | null>(null);
  const [name, setName] = useState(''); const [nameEn, setNameEn] = useState(''); const [description, setDescription] = useState(''); const [sortOrder, setSortOrder] = useState('0'); const [isActive, setIsActive] = useState(true); const [submitting, setSubmitting] = useState(false);

  const fetchCategories = async () => { setLoading(true); try { setCategories(await categoryApi.findAll(true)); setError(null); } catch { setError('Không thể tải danh sách danh mục.'); } finally { setLoading(false); } };
  useEffect(() => { void fetchCategories(); }, []);
  const openCreate = () => { setEditingId(null); setName(''); setNameEn(''); setDescription(''); setSortOrder('0'); setIsActive(true); setShowModal(true); };
  const openEdit = (category: Category) => { setEditingId(category._id); setName(category.name); setNameEn(category.nameEn || ''); setDescription(category.description || ''); setSortOrder(String(category.sortOrder)); setIsActive(category.isActive); setShowModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setSubmitting(true); setError(null); const payload = { name: name.trim(), nameEn: nameEn.trim(), description: description.trim() || undefined, sortOrder: Number.parseInt(sortOrder, 10) || 0, isActive }; try { if (editingId) await categoryApi.update(editingId, payload); else await categoryApi.create(payload); setShowModal(false); await fetchCategories(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể lưu danh mục.'); } finally { setSubmitting(false); } };
  const remove = async () => { if (!deleteTarget) return; setSubmitting(true); try { await categoryApi.remove(deleteTarget._id); setDeleteTarget(null); await fetchCategories(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể xóa danh mục.'); } finally { setSubmitting(false); } };

  return <div className="space-y-6"><PageHeader eyebrow="Menu setup" title="Danh mục thực đơn" description="Tổ chức cấu trúc menu và thứ tự hiển thị cho khách tại bàn." actions={<button onClick={openCreate} className={primaryButtonClass}><Plus aria-hidden="true" className="h-4 w-4" />Thêm danh mục</button>} />
    {error && <Feedback tone="danger">{error}</Feedback>}
    {loading ? <LoadingState label="Đang tải danh mục…" /> : categories.length === 0 ? <EmptyState icon={FolderTree} title="Chưa có danh mục" description="Tạo danh mục đầu tiên để bắt đầu xây dựng thực đơn." action={<button onClick={openCreate} className={primaryButtonClass}>Tạo danh mục</button>} /> : <>
      <div className="hidden overflow-hidden rounded-xl border border-slate-200 bg-white md:block"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-[0.1em] text-slate-500"><tr><th className="px-5 py-3.5">Danh mục</th><th className="px-5 py-3.5">Mô tả</th><th className="px-5 py-3.5 text-center">Thứ tự</th><th className="px-5 py-3.5">Trạng thái</th><th className="px-5 py-3.5 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-slate-200">{categories.map((category) => <tr key={category._id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><p className="font-semibold text-slate-950">{category.name}</p>{category.nameEn && <p className="mt-0.5 text-xs text-slate-500">{category.nameEn}</p>}</td><td className="max-w-sm px-5 py-4 text-sm text-slate-600">{category.description || 'Chưa có mô tả'}</td><td className="tabular-nums px-5 py-4 text-center text-sm font-semibold text-slate-700">{category.sortOrder}</td><td className="px-5 py-4"><StatusBadge status={category.isActive ? 'active' : 'inactive'} label={category.isActive ? 'Đang hiển thị' : 'Tạm ẩn'} /></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={() => openEdit(category)} aria-label={`Sửa ${category.name}`} className="grid h-11 w-11 place-items-center rounded-lg text-slate-600 hover:bg-brand-50 hover:text-brand-700"><Edit2 aria-hidden="true" className="h-4 w-4" /></button><button onClick={() => setDeleteTarget(category)} aria-label={`Xóa ${category.name}`} className="grid h-11 w-11 place-items-center rounded-lg text-slate-600 hover:bg-red-50 hover:text-red-700"><Trash2 aria-hidden="true" className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 md:hidden">{categories.map((category) => <article key={category._id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-slate-950">{category.name}</h2>{category.nameEn && <p className="text-xs text-slate-500">{category.nameEn}</p>}</div><StatusBadge status={category.isActive ? 'active' : 'inactive'} /></div><p className="mt-3 text-sm leading-6 text-slate-600">{category.description || 'Chưa có mô tả.'}</p><div className="mt-4 flex items-center justify-between border-t border-slate-200 pt-3"><span className="text-xs font-semibold text-slate-500">Thứ tự {category.sortOrder}</span><div className="flex gap-2"><button onClick={() => openEdit(category)} className={secondaryButtonClass}><Edit2 aria-hidden="true" className="h-4 w-4" />Sửa</button><button onClick={() => setDeleteTarget(category)} aria-label={`Xóa ${category.name}`} className="grid h-11 w-11 place-items-center rounded-lg border border-red-200 text-red-700"><Trash2 aria-hidden="true" className="h-4 w-4" /></button></div></div></article>)}</div>
    </>}
    <Modal open={showModal} onClose={() => setShowModal(false)} title={editingId ? 'Cập nhật danh mục' : 'Thêm danh mục'} description="Tên tiếng Việt là bắt buộc; tiếng Anh sẽ fallback an toàn nếu để trống." footer={<><button type="button" onClick={() => setShowModal(false)} className={secondaryButtonClass}>Hủy</button><button type="submit" form="category-form" disabled={submitting} className={primaryButtonClass}>{submitting ? 'Đang lưu…' : editingId ? 'Lưu thay đổi' : 'Thêm danh mục'}</button></>}><form id="category-form" onSubmit={submit} className="space-y-4"><label className={labelClass}>Tên danh mục <span className="text-red-600">*</span><input required value={name} onChange={(event) => setName(event.target.value)} className={`${controlClass} mt-1.5`} placeholder="Món chính, Đồ uống…" /></label><label className={labelClass}>Tên tiếng Anh<input value={nameEn} onChange={(event) => setNameEn(event.target.value)} className={`${controlClass} mt-1.5`} placeholder="Main dishes, Drinks…" /></label><label className={labelClass}>Mô tả<textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} className={`${controlClass} mt-1.5 resize-y`} /></label><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>Thứ tự hiển thị<input type="number" min="0" value={sortOrder} onChange={(event) => setSortOrder(event.target.value)} className={`${controlClass} mt-1.5`} /></label><label className="flex min-h-11 items-center gap-3 self-end rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={isActive} onChange={(event) => setIsActive(event.target.checked)} className="h-5 w-5 accent-brand-600" />Hiển thị trên menu</label></div></form></Modal>
    <ConfirmDialog open={Boolean(deleteTarget)} title="Xóa danh mục?" description={`Danh mục “${deleteTarget?.name ?? ''}” sẽ bị xóa và có thể ảnh hưởng các món đang liên kết.`} confirmLabel="Xóa danh mục" busy={submitting} onClose={() => setDeleteTarget(null)} onConfirm={() => void remove()} />
  </div>;
}
