import { useCallback, useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react';
import { Edit2, ImageOff, Plus, Search, Soup, Trash2, Upload } from 'lucide-react';
import { dishApi, type Dish } from '../../services/api/dish';
import { categoryApi, type Category } from '../../services/api/category';
import { ConfirmDialog, EmptyState, Feedback, LoadingState, Modal, PageHeader, StatusBadge, controlClass, labelClass, primaryButtonClass, secondaryButtonClass } from '../../components/ui';

const currency = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' });

export function DishManager() {
  const [dishes, setDishes] = useState<Dish[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [categoryFilter, setCategoryFilter] = useState(''); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [showModal, setShowModal] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [deleteTarget, setDeleteTarget] = useState<Dish | null>(null); const [name, setName] = useState(''); const [nameEn, setNameEn] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState(''); const [categoryId, setCategoryId] = useState(''); const [isAvailable, setIsAvailable] = useState(true); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);

  const fetchData = useCallback(async () => { setLoading(true); try { const [categoryData, dishData] = await Promise.all([categoryApi.findAll(false), dishApi.findAll(categoryFilter || undefined, true)]); setCategories(categoryData); setDishes(dishData); setError(null); } catch { setError('Không thể tải dữ liệu món ăn.'); } finally { setLoading(false); } }, [categoryFilter]);
  useEffect(() => { void fetchData(); }, [fetchData]);
  useEffect(() => () => { if (previewUrl?.startsWith('blob:')) URL.revokeObjectURL(previewUrl); }, [previewUrl]);
  const visibleDishes = useMemo(() => dishes.filter((dish) => dish.name.toLowerCase().includes(search.trim().toLowerCase())), [dishes, search]);
  const openCreate = () => { setEditingId(null); setName(''); setNameEn(''); setDescription(''); setPrice(''); setCategoryId(categories[0]?._id || ''); setIsAvailable(true); setSelectedFile(null); setPreviewUrl(null); setShowModal(true); };
  const openEdit = (dish: Dish) => { setEditingId(dish._id); setName(dish.name); setNameEn(dish.nameEn || ''); setDescription(dish.description || ''); setPrice(String(dish.price)); setCategoryId(typeof dish.categoryId === 'object' ? dish.categoryId._id : dish.categoryId); setIsAvailable(dish.isAvailable); setSelectedFile(null); setPreviewUrl(dish.imageUrl || null); setShowModal(true); };
  const chooseImage = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (previewUrl?.startsWith('blob:')) URL.revokeObjectURL(previewUrl); setSelectedFile(file); setPreviewUrl(URL.createObjectURL(file)); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim() || !price || !categoryId) return setError('Nhập đầy đủ tên, giá và danh mục.'); setSubmitting(true); setError(null); const form = new FormData(); form.append('name', name.trim()); form.append('nameEn', nameEn.trim()); form.append('description', description.trim()); form.append('price', price); form.append('categoryId', categoryId); form.append('isAvailable', String(isAvailable)); if (selectedFile) form.append('image', selectedFile); try { if (editingId) await dishApi.update(editingId, form); else await dishApi.create(form); setShowModal(false); await fetchData(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể lưu món ăn.'); } finally { setSubmitting(false); } };
  const remove = async () => { if (!deleteTarget) return; setSubmitting(true); try { await dishApi.remove(deleteTarget._id); setDeleteTarget(null); await fetchData(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể xóa món ăn.'); } finally { setSubmitting(false); } };

  return <div className="space-y-6"><PageHeader eyebrow="Menu catalog" title="Món ăn" description="Quản lý nội dung song ngữ, giá bán, hình ảnh và khả năng phục vụ." actions={<button onClick={openCreate} className={primaryButtonClass}><Plus aria-hidden="true" className="h-4 w-4" />Thêm món ăn</button>} />
    <section aria-label="Lọc món ăn" className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_16rem]"><label className="relative"><span className="sr-only">Tìm món ăn</span><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm theo tên món" className={`${controlClass} pl-10`} /></label><label><span className="sr-only">Lọc danh mục</span><select value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)} className={controlClass}><option value="">Tất cả danh mục</option>{categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></label></section>
    {error && <Feedback tone="danger">{error}</Feedback>}
    {loading ? <LoadingState label="Đang tải danh sách món…" /> : visibleDishes.length === 0 ? <EmptyState icon={Soup} title="Không có món phù hợp" description={dishes.length ? 'Thử từ khóa hoặc danh mục khác.' : 'Tạo món đầu tiên để hiển thị trên menu khách.'} action={!dishes.length ? <button onClick={openCreate} className={primaryButtonClass}>Thêm món ăn</button> : undefined} /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visibleDishes.map((dish) => { const categoryName = typeof dish.categoryId === 'object' ? dish.categoryId.name : 'Chưa phân loại'; return <article key={dish._id} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="relative aspect-[16/10] bg-slate-100">{dish.imageUrl ? <img src={dish.imageUrl} alt={dish.name} loading="lazy" className="absolute inset-0 m-auto block h-auto w-auto max-h-full max-w-full object-contain" /> : <div className="grid h-full place-items-center text-slate-400"><ImageOff aria-hidden="true" className="h-8 w-8" /></div>}<div className="absolute inset-x-3 top-3 flex items-start justify-between gap-2"><span className="rounded-md bg-slate-950/85 px-2.5 py-1 text-xs font-semibold text-white">{categoryName}</span><StatusBadge status={dish.isAvailable ? 'active' : 'inactive'} label={dish.isAvailable ? 'Còn món' : 'Hết món'} /></div></div><div className="p-4"><h2 className="line-clamp-2 font-bold text-slate-950">{dish.name}</h2>{dish.nameEn && <p className="mt-0.5 truncate text-xs text-slate-500">{dish.nameEn}</p>}<p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-slate-600">{dish.description || 'Chưa có mô tả món ăn.'}</p><p className="tabular-nums mt-3 text-lg font-black text-brand-700">{currency.format(dish.price)}</p></div><div className="flex gap-2 border-t border-slate-200 p-3"><button onClick={() => openEdit(dish)} className={`${secondaryButtonClass} flex-1`}><Edit2 aria-hidden="true" className="h-4 w-4" />Sửa</button><button onClick={() => setDeleteTarget(dish)} aria-label={`Xóa ${dish.name}`} className="grid h-11 w-11 place-items-center rounded-lg border border-red-200 text-red-700 hover:bg-red-50"><Trash2 aria-hidden="true" className="h-4 w-4" /></button></div></article>; })}</div>}
    <Modal open={showModal} onClose={() => setShowModal(false)} title={editingId ? 'Cập nhật món ăn' : 'Thêm món ăn'} description="Thông tin này xuất hiện trực tiếp trên menu tại bàn." size="lg" footer={<><button type="button" onClick={() => setShowModal(false)} className={secondaryButtonClass}>Hủy</button><button type="submit" form="dish-form" disabled={submitting} className={primaryButtonClass}>{submitting ? 'Đang lưu…' : editingId ? 'Lưu thay đổi' : 'Thêm món ăn'}</button></>}><form id="dish-form" onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>Tên món <span className="text-red-600">*</span><input required value={name} onChange={(event) => setName(event.target.value)} className={`${controlClass} mt-1.5`} /></label><label className={labelClass}>Tên tiếng Anh<input value={nameEn} onChange={(event) => setNameEn(event.target.value)} className={`${controlClass} mt-1.5`} /></label><label className={labelClass}>Danh mục <span className="text-red-600">*</span><select required value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className={`${controlClass} mt-1.5`}>{categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></label><label className={labelClass}>Giá bán (VND) <span className="text-red-600">*</span><input required min="0" type="number" inputMode="numeric" value={price} onChange={(event) => setPrice(event.target.value)} className={`${controlClass} mt-1.5`} /></label></div><label className={labelClass}>Mô tả<textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} className={`${controlClass} mt-1.5 resize-y`} /></label><fieldset><legend className={labelClass}>Ảnh món ăn</legend><div className="mt-1.5 flex flex-col gap-3 rounded-lg border border-dashed border-slate-300 p-3 sm:flex-row sm:items-center"><div className="relative aspect-[16/10] w-full shrink-0 rounded-lg bg-slate-100 text-slate-400 sm:h-24 sm:w-36">{previewUrl ? <img src={previewUrl} alt="Ảnh xem trước món ăn" className="absolute inset-0 m-auto block h-auto w-auto max-h-full max-w-full object-contain" /> : <span className="grid h-full place-items-center"><ImageOff aria-hidden="true" className="h-7 w-7" /></span>}</div><label className={`${secondaryButtonClass} w-full sm:w-auto`}><Upload aria-hidden="true" className="h-4 w-4" />Chọn ảnh<input type="file" accept="image/*" className="sr-only" onChange={chooseImage} /></label></div></fieldset><label className="flex min-h-11 items-center gap-3 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={isAvailable} onChange={(event) => setIsAvailable(event.target.checked)} className="h-5 w-5 accent-brand-600" />Món đang sẵn sàng bán</label></form></Modal>
    <ConfirmDialog open={Boolean(deleteTarget)} title="Xóa món ăn?" description={`Món “${deleteTarget?.name ?? ''}” sẽ không còn trong danh mục quản trị.`} confirmLabel="Xóa món" busy={submitting} onClose={() => setDeleteTarget(null)} onConfirm={() => void remove()} />
  </div>;
}
