import { useEffect, useState, type FormEvent } from 'react';
import { io } from 'socket.io-client';
import { Download, Edit2, Grid2X2, Plus, QrCode, RefreshCw, Trash2, Users } from 'lucide-react';
import { tableApi, type Table } from '../../services/api/table';
import { ConfirmDialog, EmptyState, Feedback, LoadingState, Modal, PageHeader, StatusBadge, controlClass, labelClass, primaryButtonClass, secondaryButtonClass } from '../../components/ui';

const socketUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000';
type TableStatus = Table['status'];

export function TableManager() {
  const [tables, setTables] = useState<Table[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState('');
  const [showModal, setShowModal] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [deleteTarget, setDeleteTarget] = useState<Table | null>(null); const [tableCode, setTableCode] = useState(''); const [capacity, setCapacity] = useState('4'); const [status, setStatus] = useState<TableStatus>('available'); const [submitting, setSubmitting] = useState(false); const [activeQrTable, setActiveQrTable] = useState<Table | null>(null);
  const user = JSON.parse(localStorage.getItem('user') || '{}') as { role?: string }; const isAdmin = user.role === 'admin';
  const fetchTables = async () => { setLoading(true); try { setTables(await tableApi.findAll()); setError(null); } catch { setError('Không thể tải danh sách bàn ăn. Kiểm tra quyền truy cập và kết nối.'); } finally { setLoading(false); } };
  useEffect(() => { void fetchTables(); }, []);
  useEffect(() => { const socket = io(socketUrl); socket.on('connect', () => { socket.emit('join', { room: 'admin' }); socket.emit('join', { room: 'waiter' }); }); socket.on('tables:updated', () => void fetchTables()); socket.on('table:grouped', () => void fetchTables()); return () => { socket.disconnect(); }; }, []);
  const openCreate = () => { setEditingId(null); setTableCode(''); setCapacity('4'); setStatus('available'); setShowModal(true); };
  const openEdit = (table: Table) => { setEditingId(table._id); setTableCode(table.tableCode); setCapacity(String(table.capacity)); setStatus(table.status); setShowModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!tableCode.trim()) return; setSubmitting(true); setError(null); try { const payload = { tableCode: tableCode.trim().toUpperCase(), capacity: Number.parseInt(capacity, 10) || 4, status }; if (editingId) await tableApi.update(editingId, payload); else await tableApi.create(payload); setShowModal(false); setSuccess(editingId ? 'Đã cập nhật thông tin bàn.' : 'Đã tạo bàn và mã QR.'); await fetchTables(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể lưu thông tin bàn.'); } finally { setSubmitting(false); } };
  const remove = async () => { if (!deleteTarget) return; setSubmitting(true); try { await tableApi.remove(deleteTarget._id); setDeleteTarget(null); setSuccess('Đã xóa bàn khỏi hệ thống.'); await fetchTables(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể xóa bàn.'); } finally { setSubmitting(false); } };
  const regenerateQr = async (id: string) => { setSubmitting(true); try { const updated = await tableApi.regenerateQr(id); setActiveQrTable(updated); setSuccess('Đã sinh lại mã QR thành công.'); await fetchTables(); } catch { setError('Không thể sinh lại mã QR.'); } finally { setSubmitting(false); } };
  const downloadQr = (table: Table) => { const link = document.createElement('a'); link.href = table.qrCodeUrl; link.download = `QR-Ban-${table.tableCode}.png`; document.body.appendChild(link); link.click(); link.remove(); };
  const tableMenuUrl = activeQrTable ? `${window.location.origin}/menu?tableId=${activeQrTable._id}` : '';

  return <div className="space-y-6"><PageHeader eyebrow="Floor setup" title="Bàn ăn & QR" description="Theo dõi trạng thái thời gian thực, cấu hình sức chứa và quản lý QR gọi món." actions={isAdmin ? <button onClick={openCreate} className={primaryButtonClass}><Plus aria-hidden="true" className="h-4 w-4" />Thêm bàn</button> : undefined} />
    {error && <Feedback tone="danger">{error}</Feedback>}{success && <Feedback tone="success">{success}</Feedback>}
    {loading ? <LoadingState label="Đang tải sơ đồ bàn…" /> : tables.length === 0 ? <EmptyState icon={Grid2X2} title="Chưa có bàn ăn" description="Tạo bàn đầu tiên để sinh QR gọi món." action={isAdmin ? <button onClick={openCreate} className={primaryButtonClass}>Tạo bàn</button> : undefined} /> : <>
      <div className="hidden overflow-hidden rounded-xl border border-slate-200 bg-white lg:block"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-[0.1em] text-slate-500"><tr><th className="px-5 py-3.5">Bàn</th><th className="px-5 py-3.5">Sức chứa</th><th className="px-5 py-3.5">Trạng thái</th><th className="px-5 py-3.5">Nhóm bàn</th><th className="px-5 py-3.5">QR gọi món</th><th className="px-5 py-3.5 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-slate-200">{tables.map((table) => <tr key={table._id} className="hover:bg-slate-50/70"><td className="px-5 py-4 text-lg font-black text-slate-950">{table.tableCode}</td><td className="px-5 py-4 text-sm text-slate-600"><span className="flex items-center gap-2"><Users aria-hidden="true" className="h-4 w-4" />{table.capacity} người</span></td><td className="px-5 py-4"><StatusBadge status={table.status} /></td><td className="px-5 py-4">{table.groupedWithTableIds?.length ? <StatusBadge status="merged" label={`Ghép ${table.groupedWithTableIds.length + 1} bàn`} /> : <span className="text-sm text-slate-400">Độc lập</span>}</td><td className="px-5 py-4"><button onClick={() => setActiveQrTable(table)} className={secondaryButtonClass}><QrCode aria-hidden="true" className="h-4 w-4" />Xem QR</button></td><td className="px-5 py-4"><div className="flex justify-end gap-2">{isAdmin && <><button onClick={() => openEdit(table)} aria-label={`Sửa bàn ${table.tableCode}`} className="grid h-11 w-11 place-items-center rounded-lg text-slate-600 hover:bg-brand-50 hover:text-brand-700"><Edit2 aria-hidden="true" className="h-4 w-4" /></button><button onClick={() => setDeleteTarget(table)} aria-label={`Xóa bàn ${table.tableCode}`} className="grid h-11 w-11 place-items-center rounded-lg text-slate-600 hover:bg-red-50 hover:text-red-700"><Trash2 aria-hidden="true" className="h-4 w-4" /></button></>}</div></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 sm:grid-cols-2 lg:hidden">{tables.map((table) => <article key={table._id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">Mã bàn</p><h2 className="mt-1 text-2xl font-black text-slate-950">{table.tableCode}</h2></div><StatusBadge status={table.status} /></div><div className="mt-3 flex items-center justify-between text-sm text-slate-600"><span className="flex items-center gap-2"><Users aria-hidden="true" className="h-4 w-4" />{table.capacity} người</span>{table.groupedWithTableIds?.length ? <StatusBadge status="merged" /> : <span>Độc lập</span>}</div><div className="mt-4 flex gap-2 border-t border-slate-200 pt-3"><button onClick={() => setActiveQrTable(table)} className={`${secondaryButtonClass} flex-1`}><QrCode aria-hidden="true" className="h-4 w-4" />Xem QR</button>{isAdmin && <><button onClick={() => openEdit(table)} aria-label={`Sửa bàn ${table.tableCode}`} className="grid h-11 w-11 place-items-center rounded-lg border border-slate-300 text-slate-700"><Edit2 aria-hidden="true" className="h-4 w-4" /></button><button onClick={() => setDeleteTarget(table)} aria-label={`Xóa bàn ${table.tableCode}`} className="grid h-11 w-11 place-items-center rounded-lg border border-red-200 text-red-700"><Trash2 aria-hidden="true" className="h-4 w-4" /></button></>}</div></article>)}</div>
    </>}
    <Modal open={Boolean(activeQrTable)} onClose={() => setActiveQrTable(null)} title={`QR gọi món · Bàn ${activeQrTable?.tableCode ?? ''}`} description="Khách quét mã này để mở đúng menu và phiên tại bàn." size="sm" footer={<><button onClick={() => activeQrTable && downloadQr(activeQrTable)} className={primaryButtonClass}><Download aria-hidden="true" className="h-4 w-4" />Tải QR</button>{isAdmin && <button onClick={() => activeQrTable && void regenerateQr(activeQrTable._id)} disabled={submitting} className={secondaryButtonClass}><RefreshCw aria-hidden="true" className={`h-4 w-4 ${submitting ? 'animate-spin' : ''}`} />Sinh lại</button>}</>}><div className="mx-auto aspect-square w-full max-w-64 rounded-xl border border-slate-200 bg-white p-3">{activeQrTable && <img src={activeQrTable.qrCodeUrl} alt={`QR gọi món bàn ${activeQrTable.tableCode}`} className="h-full w-full" />}</div><p className="mt-4 overflow-wrap-anywhere rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600"><span className="font-semibold text-slate-800">Liên kết menu:</span><br />{tableMenuUrl}</p></Modal>
    <Modal open={showModal} onClose={() => setShowModal(false)} title={editingId ? 'Cập nhật bàn ăn' : 'Thêm bàn ăn'} description="Mã bàn được chuẩn hóa thành chữ in hoa." footer={<><button type="button" onClick={() => setShowModal(false)} className={secondaryButtonClass}>Hủy</button><button type="submit" form="table-form" disabled={submitting} className={primaryButtonClass}>{submitting ? 'Đang lưu…' : editingId ? 'Lưu thay đổi' : 'Thêm bàn'}</button></>}><form id="table-form" onSubmit={submit} className="space-y-4"><label className={labelClass}>Mã bàn <span className="text-red-600">*</span><input required value={tableCode} onChange={(event) => setTableCode(event.target.value)} placeholder="A01" className={`${controlClass} mt-1.5 uppercase`} /></label><div className="grid gap-4 sm:grid-cols-2"><label className={labelClass}>Sức chứa<input type="number" min="1" value={capacity} onChange={(event) => setCapacity(event.target.value)} className={`${controlClass} mt-1.5`} /></label><label className={labelClass}>Trạng thái<select value={status} onChange={(event) => setStatus(event.target.value as TableStatus)} className={`${controlClass} mt-1.5`}><option value="available">Bàn trống</option><option value="occupied">Đang phục vụ</option><option value="waiting_payment">Chờ thanh toán</option><option value="hidden">Tạm ẩn</option></select></label></div></form></Modal>
    <ConfirmDialog open={Boolean(deleteTarget)} title="Xóa bàn ăn?" description={`Bàn ${deleteTarget?.tableCode ?? ''} và QR liên quan sẽ không thể được khách truy cập.`} confirmLabel="Xóa bàn" busy={submitting} onClose={() => setDeleteTarget(null)} onConfirm={() => void remove()} />
  </div>;
}
