import { useEffect, useState, type FormEvent } from 'react';
import { Edit2, Plus, ShieldCheck, Trash2, Users } from 'lucide-react';
import { userApi, type ManagedUser, type UserRole } from '../../services/api/user';
import { ConfirmDialog, EmptyState, Feedback, LoadingState, Modal, PageHeader, StatusBadge, controlClass, labelClass, primaryButtonClass, secondaryButtonClass } from '../../components/ui';

const roleLabels: Record<UserRole, string> = { admin: 'Quản trị viên', kitchen: 'Nhân viên bếp', waiter: 'Phục vụ' };
export function UserManager() {
  const [users, setUsers] = useState<ManagedUser[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [showModal, setShowModal] = useState(false); const [editingUser, setEditingUser] = useState<ManagedUser | null>(null); const [deleteTarget, setDeleteTarget] = useState<ManagedUser | null>(null); const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<UserRole>('kitchen'); const [isActive, setIsActive] = useState(true); const [submitting, setSubmitting] = useState(false);
  const fetchUsers = async () => { setLoading(true); try { setUsers(await userApi.findAll()); setError(null); } catch { setError('Không thể tải danh sách người dùng.'); } finally { setLoading(false); } };
  useEffect(() => { void fetchUsers(); }, []);
  const openCreate = () => { setEditingUser(null); setFullName(''); setEmail(''); setPassword(''); setRole('kitchen'); setIsActive(true); setShowModal(true); };
  const openEdit = (user: ManagedUser) => { setEditingUser(user); setFullName(user.fullName); setEmail(user.email); setPassword(''); setRole(user.role); setIsActive(user.isActive); setShowModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!editingUser && password.length < 6) return setError('Mật khẩu phải có ít nhất 6 ký tự.'); setSubmitting(true); setError(null); try { const payload = { fullName: fullName.trim(), email: email.trim(), role, isActive }; if (editingUser) await userApi.update(editingUser.id, password ? { ...payload, password } : payload); else await userApi.create({ ...payload, password }); setShowModal(false); await fetchUsers(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể lưu người dùng.'); } finally { setSubmitting(false); } };
  const remove = async () => { if (!deleteTarget) return; setSubmitting(true); try { await userApi.remove(deleteTarget.id); setDeleteTarget(null); await fetchUsers(); } catch (requestError) { setError((requestError as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể xóa người dùng.'); } finally { setSubmitting(false); } };
  return <div className="space-y-6"><PageHeader eyebrow="Access control" title="Người dùng & phân quyền" description="Quản lý tài khoản cho quản trị viên, bếp và nhân viên phục vụ." actions={<button onClick={openCreate} className={primaryButtonClass}><Plus aria-hidden="true" className="h-4 w-4" />Thêm người dùng</button>} />
    {error && <Feedback tone="danger">{error}</Feedback>}
    {loading ? <LoadingState label="Đang tải người dùng…" /> : users.length === 0 ? <EmptyState icon={Users} title="Chưa có người dùng" action={<button onClick={openCreate} className={primaryButtonClass}>Thêm người dùng</button>} /> : <><div className="hidden overflow-hidden rounded-xl border border-slate-200 bg-white md:block"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-[0.1em] text-slate-500"><tr><th className="px-5 py-3.5">Nhân viên</th><th className="px-5 py-3.5">Vai trò</th><th className="px-5 py-3.5">Trạng thái</th><th className="px-5 py-3.5 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-slate-200">{users.map((user) => <tr key={user.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><p className="font-semibold text-slate-950">{user.fullName}</p><p className="mt-0.5 text-sm text-slate-500">{user.email}</p></td><td className="px-5 py-4"><span className="inline-flex items-center gap-2 text-sm font-semibold text-slate-700"><ShieldCheck aria-hidden="true" className="h-4 w-4 text-brand-700" />{roleLabels[user.role]}</span></td><td className="px-5 py-4"><StatusBadge status={user.isActive ? 'active' : 'inactive'} label={user.isActive ? 'Hoạt động' : 'Đã khóa'} /></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={() => openEdit(user)} aria-label={`Sửa ${user.email}`} className="grid h-11 w-11 place-items-center rounded-lg text-slate-600 hover:bg-brand-50 hover:text-brand-700"><Edit2 aria-hidden="true" className="h-4 w-4" /></button><button onClick={() => setDeleteTarget(user)} aria-label={`Xóa ${user.email}`} className="grid h-11 w-11 place-items-center rounded-lg text-slate-600 hover:bg-red-50 hover:text-red-700"><Trash2 aria-hidden="true" className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{users.map((user) => <article key={user.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-bold text-slate-950">{user.fullName}</h2><p className="truncate text-sm text-slate-500">{user.email}</p></div><StatusBadge status={user.isActive ? 'active' : 'inactive'} /></div><p className="mt-3 flex items-center gap-2 text-sm font-semibold text-slate-700"><ShieldCheck aria-hidden="true" className="h-4 w-4 text-brand-700" />{roleLabels[user.role]}</p><div className="mt-4 flex gap-2 border-t border-slate-200 pt-3"><button onClick={() => openEdit(user)} className={`${secondaryButtonClass} flex-1`}><Edit2 aria-hidden="true" className="h-4 w-4" />Sửa</button><button onClick={() => setDeleteTarget(user)} aria-label={`Xóa ${user.email}`} className="grid h-11 w-11 place-items-center rounded-lg border border-red-200 text-red-700"><Trash2 aria-hidden="true" className="h-4 w-4" /></button></div></article>)}</div></>}
    <Modal open={showModal} onClose={() => setShowModal(false)} title={editingUser ? 'Cập nhật người dùng' : 'Thêm người dùng'} description="Vai trò quyết định màn hình và nghiệp vụ tài khoản có thể truy cập." footer={<><button type="button" onClick={() => setShowModal(false)} className={secondaryButtonClass}>Hủy</button><button type="submit" form="user-form" disabled={submitting} className={primaryButtonClass}>{submitting ? 'Đang lưu…' : 'Lưu người dùng'}</button></>}><form id="user-form" onSubmit={submit} className="space-y-4"><label className={labelClass}>Họ và tên <span className="text-red-600">*</span><input required autoComplete="name" value={fullName} onChange={(event) => setFullName(event.target.value)} className={`${controlClass} mt-1.5`} /></label><label className={labelClass}>Email <span className="text-red-600">*</span><input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className={`${controlClass} mt-1.5`} /></label><label className={labelClass}>Mật khẩu {!editingUser && <span className="text-red-600">*</span>}{editingUser && <span className="font-normal text-slate-500"> · để trống nếu không đổi</span>}<input required={!editingUser} minLength={6} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} className={`${controlClass} mt-1.5`} /></label><label className={labelClass}>Vai trò<select value={role} onChange={(event) => setRole(event.target.value as UserRole)} className={`${controlClass} mt-1.5`}><option value="admin">Quản trị viên</option><option value="kitchen">Nhân viên bếp</option><option value="waiter">Phục vụ</option></select></label><label className="flex min-h-11 items-center gap-3 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={isActive} onChange={(event) => setIsActive(event.target.checked)} className="h-5 w-5 accent-brand-600" />Cho phép tài khoản đăng nhập</label></form></Modal>
    <ConfirmDialog open={Boolean(deleteTarget)} title="Xóa tài khoản?" description={`Tài khoản ${deleteTarget?.email ?? ''} sẽ mất quyền truy cập ngay sau khi xóa.`} confirmLabel="Xóa tài khoản" busy={submitting} onClose={() => setDeleteTarget(null)} onConfirm={() => void remove()} />
  </div>;
}
