import { createHash } from 'node:crypto';
import { Types } from 'mongoose';
import type { Dish } from '../../src/modules/dish/dish.schema';
import type { Category } from '../../src/modules/category/category.schema';
import type {
  ALLERGEN_TAGS,
  DISH_MODIFIERS,
} from '../../src/modules/dish/dish-metadata';

export const DATASET_ID = 'smartorder-ai-demo-v1';
export const DEMO_LABEL = 'SYNTHETIC DEVELOPMENT/DEMO DATA';
export const ANCHOR = new Date('2026-09-01T00:00:00.000Z');
export const fixtureId = (key: string): Types.ObjectId =>
  new Types.ObjectId(
    createHash('sha256')
      .update(`${DATASET_ID}:${key}`)
      .digest('hex')
      .slice(0, 24),
  );

type Allergen = (typeof ALLERGEN_TAGS)[number];
type Modifier = (typeof DISH_MODIFIERS)[number];
type Ingredient = {
  vi: string;
  en: string;
  allergens: Allergen[];
  animal?: 'meat' | 'egg-milk';
};
const ingredient = (
  vi: string,
  en: string,
  allergens: Allergen[] = [],
  animal?: Ingredient['animal'],
): Ingredient => ({ vi, en, allergens, animal });

// Authored demo recipes, including sauces/toppings. These are NOT declarations
// about a real restaurant's recipes, cross-contact, or allergy safety.
export const INGREDIENTS = {
  beef: ingredient('thịt bò', 'beef', [], 'meat'),
  chicken: ingredient('thịt gà', 'chicken', [], 'meat'),
  pork: ingredient('thịt heo', 'pork', [], 'meat'),
  shrimp: ingredient('tôm', 'shrimp', ['shellfish'], 'meat'),
  squid: ingredient('mực', 'squid', ['shellfish'], 'meat'),
  fish: ingredient('cá basa', 'basa fish', ['fish'], 'meat'),
  fishSauce: ingredient('nước mắm cá', 'fish sauce', ['fish'], 'meat'),
  shrimpPaste: ingredient(
    'mắm ruốc',
    'fermented shrimp paste',
    ['shellfish'],
    'meat',
  ),
  egg: ingredient('trứng gà', 'egg', ['egg'], 'egg-milk'),
  milk: ingredient('sữa đặc', 'condensed milk', ['milk'], 'egg-milk'),
  yogurt: ingredient('sữa chua', 'yogurt', ['milk'], 'egg-milk'),
  tofu: ingredient('đậu hũ', 'tofu', ['soy']),
  soySauce: ingredient('nước tương có lúa mì', 'wheat-containing soy sauce', [
    'soy',
    'gluten',
  ]),
  peanut: ingredient('đậu phộng rang', 'roasted peanuts', ['peanut']),
  cashew: ingredient('hạt điều', 'cashews', ['tree-nut']),
  sesame: ingredient('mè rang', 'toasted sesame', ['sesame']),
  noodles: ingredient('bánh phở gạo', 'rice pho noodles'),
  vermicelli: ingredient('bún gạo', 'rice vermicelli'),
  eggNoodles: ingredient(
    'mì trứng lúa mì',
    'wheat egg noodles',
    ['egg', 'gluten'],
    'egg-milk',
  ),
  rice: ingredient('gạo tẻ', 'white rice'),
  stickyRice: ingredient('gạo nếp', 'sticky rice'),
  ricePaper: ingredient('bánh tráng gạo', 'rice paper'),
  flour: ingredient('bột mì', 'wheat flour', ['gluten']),
  onion: ingredient('hành lá', 'spring onion'),
  shallot: ingredient('hành tím', 'shallot'),
  garlic: ingredient('tỏi', 'garlic'),
  ginger: ingredient('gừng', 'ginger'),
  lemongrass: ingredient('sả', 'lemongrass'),
  chili: ingredient('ớt tươi', 'fresh chili'),
  pepper: ingredient('tiêu đen', 'black pepper'),
  lime: ingredient('chanh', 'lime'),
  herbs: ingredient('rau thơm', 'fresh herbs'),
  lettuce: ingredient('xà lách', 'lettuce'),
  sprouts: ingredient('giá đỗ', 'mung bean sprouts'),
  carrot: ingredient('cà rốt', 'carrot'),
  cucumber: ingredient('dưa leo', 'cucumber'),
  tomato: ingredient('cà chua', 'tomato'),
  pineapple: ingredient('thơm', 'pineapple'),
  mushroom: ingredient('nấm rơm', 'straw mushrooms'),
  greens: ingredient('rau muống', 'water spinach'),
  cabbage: ingredient('bắp cải', 'cabbage'),
  lotus: ingredient('ngó sen', 'lotus stems'),
  pumpkin: ingredient('bí đỏ', 'pumpkin'),
  corn: ingredient('bắp ngọt', 'sweet corn'),
  mungBean: ingredient('đậu xanh', 'mung beans'),
  coconut: ingredient('nước cốt dừa', 'coconut milk'),
  banana: ingredient('chuối', 'banana'),
  mango: ingredient('xoài', 'mango'),
  orange: ingredient('cam', 'orange'),
  peach: ingredient('đào', 'peach'),
  tea: ingredient('trà lài', 'jasmine tea'),
  coffee: ingredient('cà phê', 'coffee'),
  sugar: ingredient('đường mía', 'cane sugar'),
  salt: ingredient('muối', 'salt'),
  oil: ingredient('dầu hướng dương', 'sunflower oil'),
  water: ingredient('nước lọc', 'water'),
  ice: ingredient('đá viên', 'ice'),
} satisfies Record<string, Ingredient>;

export type RecipeKey = keyof typeof INGREDIENTS;
type Recipe = [
  key: string,
  vi: string,
  en: string,
  price: number,
  ingredients: string,
  spice: number,
  portion: string,
  methodVi: string,
  methodEn: string,
  modifiers: Modifier[],
];
export const CATEGORY_NAMES = [
  ['Phở và món nước', 'Pho and soups'],
  ['Cơm', 'Rice dishes'],
  ['Bún và mì', 'Vermicelli and noodles'],
  ['Khai vị', 'Starters'],
  ['Món chay và rau', 'Vegetarian dishes and vegetables'],
  ['Món ăn chung', 'Sharing dishes'],
  ['Tráng miệng', 'Desserts'],
  ['Đồ uống', 'Drinks'],
];

// Five recipes per category. Spice describes the default recipe; modifiers are
// only listed when this recipe can actually accommodate the preparation change.
const RECIPES: Recipe[] = [
  [
    'pho-bo',
    'Phở bò tái',
    'Rare beef pho',
    69000,
    'beef noodles fishSauce onion ginger herbs salt water',
    0,
    '1 tô / bowl',
    'Phở nước dùng bò với gừng và rau thơm',
    'Beef broth pho with ginger and herbs',
    ['NO_ONION', 'EXTRA_NOODLES'],
  ],
  [
    'pho-ga',
    'Phở gà',
    'Chicken pho',
    59000,
    'chicken noodles fishSauce onion ginger herbs salt water',
    0,
    '1 tô / bowl',
    'Phở gà xé với nước dùng gừng',
    'Shredded chicken pho in ginger broth',
    ['NO_ONION', 'EXTRA_NOODLES'],
  ],
  [
    'bun-bo',
    'Bún bò Huế',
    'Hue spicy beef soup',
    75000,
    'beef pork vermicelli shrimpPaste fishSauce lemongrass chili onion herbs salt water',
    3,
    '1 tô / bowl',
    'Bún bò nước dùng sả và mắm ruốc, ớt nấu trong nước dùng',
    'Beef vermicelli with lemongrass, shrimp paste and chili cooked into the broth',
    ['NO_ONION', 'EXTRA_NOODLES'],
  ],
  [
    'canh-chua',
    'Canh chua cá',
    'Sweet and sour fish soup',
    89000,
    'fish fishSauce tomato pineapple sprouts herbs sugar salt water',
    0,
    '1 tô, 2 người / bowl for 2',
    'Canh cá chua dịu từ cà chua và thơm',
    'Fish soup with tomato and pineapple sourness',
    [],
  ],
  [
    'sup-bap',
    'Súp bắp nấm',
    'Corn and mushroom soup',
    39000,
    'corn mushroom carrot onion salt water',
    0,
    '1 chén / cup',
    'Súp bắp ngọt với nấm và cà rốt',
    'Sweet corn soup with mushrooms and carrot',
    ['NO_ONION'],
  ],
  [
    'com-tam',
    'Cơm tấm sườn',
    'Broken rice with pork chop',
    65000,
    'rice pork fishSauce soySauce garlic sugar cucumber tomato onion oil',
    0,
    '1 đĩa / plate',
    'Cơm với sườn nướng ướp nước tương và nước mắm',
    'Rice with pork chop marinated in soy and fish sauces',
    ['NO_ONION'],
  ],
  [
    'com-ga',
    'Cơm gà gừng',
    'Ginger chicken rice',
    62000,
    'rice chicken ginger fishSauce cucumber onion salt oil',
    0,
    '1 đĩa / plate',
    'Cơm gà hấp gừng với dưa leo',
    'Ginger steamed chicken and rice with cucumber',
    ['NO_ONION'],
  ],
  [
    'com-chien',
    'Cơm chiên hải sản',
    'Seafood fried rice',
    79000,
    'rice shrimp squid egg soySauce carrot onion oil pepper',
    1,
    '1 đĩa / plate',
    'Cơm chiên tôm mực, trứng và tiêu',
    'Rice fried with shrimp, squid, egg and pepper',
    ['NO_ONION', 'NO_PEPPER'],
  ],
  [
    'com-bo',
    'Cơm bò lúc lắc',
    'Shaking beef rice',
    89000,
    'rice beef soySauce garlic tomato onion pepper oil',
    1,
    '1 đĩa / plate',
    'Cơm với bò áp chảo sốt nước tương',
    'Rice with seared beef in soy sauce',
    ['NO_ONION', 'NO_PEPPER'],
  ],
  [
    'com-dau',
    'Cơm đậu hũ nấm',
    'Tofu and mushroom rice',
    49000,
    'rice tofu mushroom soySauce carrot onion oil',
    0,
    '1 đĩa / plate',
    'Cơm với đậu hũ và nấm kho nước tương',
    'Rice with soy-braised tofu and mushrooms',
    ['NO_ONION'],
  ],
  [
    'bun-thit',
    'Bún thịt nướng',
    'Grilled pork vermicelli',
    62000,
    'vermicelli pork fishSauce garlic sugar peanut lettuce herbs cucumber oil',
    0,
    '1 tô / bowl',
    'Bún thịt nướng kèm rau và đậu phộng rắc sau cùng',
    'Grilled pork vermicelli with greens and peanut topping',
    ['NO_PEANUT', 'EXTRA_NOODLES'],
  ],
  [
    'bun-cha',
    'Bún chả',
    'Hanoi grilled pork and noodles',
    69000,
    'vermicelli pork fishSauce garlic sugar carrot lettuce herbs pepper oil',
    1,
    '1 phần / serving',
    'Thịt nướng ướp tiêu với bún và nước mắm pha',
    'Pepper-marinated grilled pork with noodles and fish sauce dip',
    ['EXTRA_NOODLES'],
  ],
  [
    'mi-xao',
    'Mì xào bò',
    'Stir-fried beef egg noodles',
    75000,
    'eggNoodles beef soySauce cabbage carrot onion oil pepper',
    1,
    '1 đĩa / plate',
    'Mì trứng xào bò và rau củ',
    'Egg noodles stir-fried with beef and vegetables',
    ['NO_ONION', 'NO_PEPPER', 'EXTRA_NOODLES'],
  ],
  [
    'bun-chay',
    'Bún đậu hũ sả',
    'Lemongrass tofu vermicelli',
    49000,
    'vermicelli tofu soySauce lemongrass peanut lettuce herbs cucumber oil',
    0,
    '1 tô / bowl',
    'Bún đậu hũ áp chảo sả với đậu phộng rắc riêng',
    'Vermicelli with lemongrass tofu and peanut topping',
    ['NO_PEANUT', 'EXTRA_NOODLES'],
  ],
  [
    'mi-cay',
    'Mì hải sản cay',
    'Spicy seafood egg noodles',
    85000,
    'eggNoodles shrimp squid fishSauce chili cabbage onion salt water',
    4,
    '1 tô / bowl',
    'Mì trứng hải sản với ớt thêm theo phần khi nấu',
    'Seafood egg noodle soup with chili added per serving',
    ['NO_ONION', 'LESS_SPICY', 'NO_CHILI', 'EXTRA_NOODLES'],
  ],
  [
    'goi-cuon',
    'Gỏi cuốn tôm',
    'Fresh shrimp rice paper rolls',
    45000,
    'ricePaper vermicelli shrimp lettuce herbs peanut soySauce sugar',
    0,
    '2 cuốn / rolls',
    'Cuốn tôm rau, sốt nước tương có đậu phộng xay sẵn',
    'Fresh shrimp rolls with premixed peanut and soy dip',
    [],
  ],
  [
    'cha-gio',
    'Chả giò heo',
    'Crispy pork spring rolls',
    49000,
    'ricePaper pork carrot mushroom fishSauce garlic oil sugar',
    0,
    '4 cuốn / rolls',
    'Chả giò heo chiên giòn ăn với nước mắm pha',
    'Crispy pork rolls served with fish sauce dip',
    [],
  ],
  [
    'goi-sen',
    'Gỏi ngó sen tôm',
    'Lotus stem shrimp salad',
    69000,
    'lotus shrimp fishSauce carrot herbs lime sugar peanut chili',
    2,
    '1 đĩa, 2 người / plate for 2',
    'Gỏi ngó sen trộn tôm, ớt và đậu phộng rắc',
    'Lotus stems and shrimp tossed with chili and peanut topping',
    ['NO_PEANUT', 'LESS_SPICY', 'NO_CHILI'],
  ],
  [
    'banh-xeo',
    'Bánh xèo tôm thịt',
    'Shrimp and pork crispy pancake',
    79000,
    'rice shrimp pork coconut sprouts onion lettuce fishSauce oil sugar',
    0,
    '1 bánh / pancake',
    'Bánh từ gạo xay, nhân tôm thịt, ăn với rau và nước mắm',
    'Ground-rice pancake with shrimp and pork, greens and fish sauce',
    ['NO_ONION'],
  ],
  [
    'dau-gion',
    'Đậu hũ chiên giòn',
    'Crispy tofu bites',
    39000,
    'tofu soySauce garlic oil',
    0,
    '1 đĩa / plate',
    'Đậu hũ chiên với nước tương tỏi',
    'Fried tofu with garlic soy dip',
    [],
  ],
  [
    'rau-muong',
    'Rau muống xào tỏi',
    'Garlic water spinach',
    45000,
    'greens garlic salt oil',
    0,
    '1 đĩa, 2 người / plate for 2',
    'Rau muống xào tỏi, nêm muối',
    'Water spinach stir-fried with garlic and salt',
    [],
  ],
  [
    'nam-kho',
    'Nấm kho tiêu',
    'Pepper-braised mushrooms',
    55000,
    'mushroom soySauce pepper sugar oil',
    2,
    '1 phần / serving',
    'Nấm kho nước tương với tiêu nấu trong sốt',
    'Mushrooms braised in soy sauce with pepper cooked into the sauce',
    [],
  ],
  [
    'dau-sa',
    'Đậu hũ sả ớt',
    'Chili lemongrass tofu',
    49000,
    'tofu lemongrass chili soySauce garlic oil',
    3,
    '1 đĩa / plate',
    'Đậu hũ xào sả, ớt thêm theo phần',
    'Tofu stir-fried with lemongrass and chili added per serving',
    ['LESS_SPICY', 'NO_CHILI'],
  ],
  [
    'salad-dieu',
    'Salad xoài hạt điều',
    'Mango cashew salad',
    59000,
    'mango cashew lettuce carrot lime sugar sesame',
    0,
    '1 đĩa / plate',
    'Salad xoài hạt điều với sốt chanh và mè',
    'Mango and cashew salad with lime dressing and sesame',
    [],
  ],
  [
    'bi-do',
    'Bí đỏ hấp mè',
    'Steamed pumpkin with sesame',
    39000,
    'pumpkin sesame salt',
    0,
    '1 đĩa / plate',
    'Bí đỏ hấp, rắc mè rang và chút muối',
    'Steamed pumpkin with toasted sesame and a little salt',
    [],
  ],
  [
    'ca-kho',
    'Cá kho tộ',
    'Clay pot caramelized fish',
    119000,
    'fish fishSauce sugar shallot pepper oil water',
    1,
    '1 thố, 2 người / pot for 2',
    'Cá kho nước mắm và tiêu trong thố',
    'Fish braised in fish sauce and pepper',
    [],
  ],
  [
    'ga-sa',
    'Gà xào sả ớt',
    'Chili lemongrass chicken',
    99000,
    'chicken fishSauce lemongrass chili garlic sugar oil',
    3,
    '1 đĩa, 2 người / plate for 2',
    'Gà xào sả với ớt thêm theo phần',
    'Chicken stir-fried with lemongrass and chili added per serving',
    ['LESS_SPICY', 'NO_CHILI'],
  ],
  [
    'tom-rim',
    'Tôm rim mặn ngọt',
    'Sweet and savory shrimp',
    129000,
    'shrimp fishSauce sugar garlic oil',
    0,
    '1 đĩa, 2 người / plate for 2',
    'Tôm rim nước mắm đường và tỏi',
    'Shrimp glazed with fish sauce, sugar and garlic',
    [],
  ],
  [
    'muc-cay',
    'Mực xào ớt hiểm',
    'Fiery bird chili squid',
    139000,
    'squid fishSauce chili garlic onion oil',
    5,
    '1 đĩa, 2 người / plate for 2',
    'Mực xào ớt hiểm tươi, rất cay, ớt thêm lúc xào',
    'Squid stir-fried with fresh bird chili, intensely spicy, chili added during frying',
    ['NO_ONION', 'LESS_SPICY', 'NO_CHILI'],
  ],
  [
    'bo-dieu',
    'Bò xào hạt điều',
    'Beef with cashews',
    129000,
    'beef cashew soySauce onion carrot garlic pepper oil',
    1,
    '1 đĩa, 2 người / plate for 2',
    'Bò xào hạt điều, cà rốt và tiêu',
    'Beef stir-fried with cashews, carrot and pepper',
    ['NO_ONION', 'NO_PEPPER'],
  ],
  [
    'che-dau',
    'Chè đậu xanh',
    'Mung bean coconut pudding',
    29000,
    'mungBean coconut sugar water',
    0,
    '1 chén / cup',
    'Chè đậu xanh nấu sẵn với đường và nước cốt dừa',
    'Mung bean pudding precooked with sugar and coconut milk',
    [],
  ],
  [
    'chuoi-nuong',
    'Chuối nếp nướng',
    'Grilled sticky rice banana',
    35000,
    'banana stickyRice coconut sugar peanut',
    0,
    '1 phần / serving',
    'Chuối bọc nếp nướng với cốt dừa và đậu phộng rắc',
    'Grilled sticky rice wrapped banana with coconut sauce and peanut topping',
    ['NO_PEANUT'],
  ],
  [
    'flan',
    'Bánh flan',
    'Caramel custard',
    25000,
    'egg milk sugar water',
    0,
    '1 bánh / custard',
    'Bánh trứng sữa hấp với caramel nấu sẵn',
    'Steamed egg and milk custard with prepared caramel',
    [],
  ],
  [
    'xoi-xoai',
    'Xôi xoài',
    'Mango sticky rice',
    45000,
    'stickyRice mango coconut sugar sesame',
    0,
    '1 phần / serving',
    'Xôi với xoài chín, cốt dừa ngọt và mè',
    'Sticky rice with ripe mango, sweet coconut sauce and sesame',
    [],
  ],
  [
    'sua-chua',
    'Sữa chua xoài',
    'Mango yogurt',
    35000,
    'yogurt mango sugar',
    0,
    '1 ly / glass',
    'Sữa chua xoài với đường thêm theo phần',
    'Mango yogurt with sugar added per serving',
    ['LESS_SUGAR', 'NO_SUGAR'],
  ],
  [
    'tra-dao',
    'Trà đào',
    'Peach jasmine tea',
    35000,
    'tea peach sugar water ice',
    0,
    '350 ml',
    'Trà lài với đào tươi, đường và đá thêm khi pha',
    'Jasmine tea with fresh peach, sugar and ice added to order',
    ['NO_ICE', 'LESS_ICE', 'LESS_SUGAR', 'NO_SUGAR'],
  ],
  [
    'ca-phe-sua',
    'Cà phê sữa đá',
    'Iced condensed milk coffee',
    32000,
    'coffee milk water ice',
    0,
    '200 ml',
    'Cà phê với sữa đặc có đường, phục vụ cùng đá',
    'Coffee with sweetened condensed milk, served over ice',
    ['NO_ICE', 'LESS_ICE'],
  ],
  [
    'nuoc-cam',
    'Nước cam',
    'Fresh orange juice',
    39000,
    'orange sugar ice',
    0,
    '300 ml',
    'Cam vắt, đường và đá thêm theo yêu cầu',
    'Freshly squeezed orange with sugar and ice added to order',
    ['NO_ICE', 'LESS_ICE', 'LESS_SUGAR', 'NO_SUGAR'],
  ],
  [
    'tra-chanh',
    'Trà chanh',
    'Lime jasmine tea',
    25000,
    'tea lime sugar water ice',
    0,
    '350 ml',
    'Trà lài pha chanh tươi, đường và đá',
    'Jasmine tea with fresh lime, sugar and ice',
    ['NO_ICE', 'LESS_ICE', 'LESS_SUGAR', 'NO_SUGAR'],
  ],
  [
    'ca-phe-den',
    'Cà phê đen đá',
    'Iced black coffee',
    29000,
    'coffee sugar water ice',
    0,
    '200 ml',
    'Cà phê đen, đường và đá thêm khi pha',
    'Black coffee with sugar and ice added to order',
    ['NO_ICE', 'LESS_ICE', 'LESS_SUGAR', 'NO_SUGAR'],
  ],
];

export type DemoDish = Dish & {
  _id: Types.ObjectId;
  recipeKey: string;
  recipeIngredients: RecipeKey[];
};
export function buildCatalog(): {
  categories: (Category & { _id: Types.ObjectId })[];
  dishes: DemoDish[];
} {
  const categories = CATEGORY_NAMES.map(([name, nameEn], index) => ({
    _id: fixtureId(`category:${index}`),
    name: `[DEMO] ${name}`,
    nameEn: `[DEMO] ${nameEn}`,
    description: DEMO_LABEL,
    sortOrder: index,
    isActive: true,
  }));
  const dishes = RECIPES.map(
    (
      [
        key,
        name,
        nameEn,
        price,
        ingredientKeys,
        spiceLevel,
        servingSize,
        vi,
        en,
        availableModifiers,
      ],
      index,
    ) => {
      const recipeIngredients = ingredientKeys.split(' ') as RecipeKey[];
      const recipe: Ingredient[] = recipeIngredients.map(
        (id) => INGREDIENTS[id],
      );
      const meat = recipe.some((item) => item.animal === 'meat');
      const eggMilk = recipe.some((item) => item.animal === 'egg-milk');
      return {
        _id: fixtureId(`dish:${key}`),
        recipeKey: key,
        recipeIngredients,
        name,
        nameEn,
        description: `[${DEMO_LABEL}] ${vi}.`,
        descriptionEn: `[${DEMO_LABEL}] ${en}.`,
        price,
        categoryId: categories[Math.floor(index / 5)]._id,
        ingredients: recipe.map((item) => `${item.vi} / ${item.en}`),
        allergenTags: [
          ...new Set(recipe.flatMap((item) => item.allergens)),
        ].sort(),
        dietaryTags: meat
          ? ['contains-meat']
          : eggMilk
            ? ['vegetarian', 'lacto-ovo-vegetarian']
            : ['vegetarian', 'vegan'],
        spiceLevel,
        servingSize,
        availableModifiers,
        isAvailable: !['muc-cay', 'xoi-xoai', 'sup-bap'].includes(key),
      };
    },
  );
  return { categories, dishes };
}
